#!/bin/sh

#########################################################################
# Copyright (C) 2014  Wojciech Siewierski                               #
#                                                                       #
# This program is free software: you can redistribute it and/or modify  #
# it under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or     #
# (at your option) any later version.                                   #
#                                                                       #
# This program is distributed in the hope that it will be useful,       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
# GNU General Public License for more details.                          #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see <http://www.gnu.org/licenses/>. #
#########################################################################

if which rlwrap > /dev/null 2>&1; then
    COMMAND="rlwrap -H /dev/null nc"
else
    COMMAND="nc"
fi

if [ "$1" = "--no-readline" ]; then
    shift
    COMMAND="nc"
fi

if [ "$#" != 1 ]; then
    cat <<EOF
usage: $0 [ --no-readline ] PORT
    PORT -- port on which to listen
    --no-readline -- disable readline support even with rlwrap installed
EOF
    exit 1
fi

$COMMAND -l $1
